language: java
jdk:
- oraclejdk8
after_success:
- bash <(curl -s https://codecov.io/bash)
services:
  - postgresql
before_script:
- psql -U postgres -c 'CREATE DATABASE dashboarddb;'
- psql -U postgres -d dashboarddb -a -f ./postgres/citizens.sql
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 3 # give xvfb some time to start